DriveLabel:
  Type: 
    string #check for max length if type is string
  Range:
    max: 20
    min: MINSTRING
ModuleName:
  Type: 
    char
  Range:
    max: Z
    min: A
DriveName:
  Type: 
    char
  Range:
    max: Z
    min: A
IdentifyNumber:
  Type: 
    uint32
  Range:
    max: MAXUINT32
    min: MINUINT32
Variant_CRC:
  Type: 
    uint32
  Range:
    max: MAXUINT32
    min: MINUINT32
