GlobalName:
  VariantArea.VariantData.MotorVariant[<index>]
General:
  SavelastDACvalue:
    Type:
      uint8
    Range:
      max: 1
      min: 0
    ValidCallback:
      range
  EmergencyStopTaskEnable:
    Type:
      uint8
    Range:
      max: 1
      min: 0
    ValidCallback:
      range
  NotMoveTaskEnable:
    Type:
      uint8
    Range:
      max: 1
      min: 0
    ValidCallback:
      range
PosInformer_Cycle:
  PosInformer_Cycle[6]:
    Type:
      uint32
    Range:
      max: MAX
      min: MIN
    ValidCallback:
      range
TrajecotryGen_Cycle:
  TrajectoryGen_Cycle[2]:
    Type:
      uint32
    Range:
      max: MAX
      min: MIN
    ValidCallback:
      range
PiezoIncTask_Cycle:
  PiezoIncTask_Cycle[3]:
    Type:
      uint32
    Range:
      max: MAX
      min: MIN
    ValidCallback:
      range

  

# check value in range: range
# check value of string is less then max characters: string
# check value is in list: list
# if list: replace max and min with a list of valid values
# for example: 
#
# DriveLabel:
#   Type:
#     char/uint8
#   Range:
#     - A/4
#     - B/7
#     - C/8
