Motor Variant:
  categories: 
    - Type
    - BaseCtrlType
    - DriveLabel
    - ModuleName
    - DriveName
    - MotorType
  config:
    Type:
      data_type: uint
      valid_range: range
      min_value: 0
      max_value: 10
    BaseCtrlType:
      data_type: uint
      valid_range: range
      min_value: 0
      max_value: 10
    DriveLabel:
      data_type: uint
      valid_range: discrete
      values:
        - A
        - B
        - C
    ModuleName:
      data_type: uint
      valid_range: discrete
      values:
        - A
        - B
        - C
    DriveName:
      data_type: uint
      valid_range: range
      min_value: 0
      max_value: 10
    MotorType:
      data_type: uint
      valid_range: range
      min_value: 0
      max_value: 10