GlobalName:
  VariantArea.VariantData.MotorVariant[<index>]
Type:
  Type:
    int8
  Range:
    max: 2
    min: 1
  ValidCallback:
    range
DriveLabel:
  Type:
    string #check for max length if type is string
  Range:
    max: 20
    min: MIN
  ValidCallback:
    string
ModuleName:
  Type:
    char
  Range:
    max: Z
    min: A
  ValidCallback:
    range
DriveName:
  Type:
    char
  Range:
    max: Z
    min: A
  ValidCallback:
   range

# check if a value is in range: ValidCallback has to be "range"
# check if a String has less then MAX chars: ValidCallback has to be "string"
# check if a value is in the list of valid values: ValidCallback has to be "list"
# if list: replace max and min with a list of valid values
# for example: 
#
# DriveLabel:
#   Type:
#     char/uint8
#   Range:
#     - A/4
#     - B/7
#     - C/8
#   ValidCallback:
#     list
