Pivot Bearing:
  TypeList:
    - General
    - Controll[2]
    - DriveParam
    - SavePosition[15]

General:
    MagicNumber: 
      Type:
        uint8
      Range:
        max: MAXUINT8
        min: MINUINT8
    Encoder_TicksPerRevolution: 
      Type:
        uint32
      Range:
        max: MAXUINT32
        min: MINUINT32
    mEncoder_Ticks_PerMM: 
      Type:
        uint32
      Range:
        max: MAXUINT32
        min: MINUINT32
    Hallsensor_TicksPerRevolution: 
      Type:
        uint32
      Range:
        max: MAXUINT32
        min: MINUINT32
Controll:
    KP:
      Type:
        uint8
      Range:
        max: MAXUINT8
        min: MINUINT8
    KI:
      Type:
        uint8
      Range:
        max: MAXUINT8
        min: MINUINT8
    
    KD:
      Type:
        uint8
      Range:
        max: MAXUINT8
        min: MINUINT8
    MinOutLimit:
      Type:
        uint8
      Range:
        max: MAXUINT8
        min: MINUINT8
    MaxOutLimit:
      Type:
        uint8
      Range:
        max: MAXUINT8
        min: MINUINT8
    MinIntegratorLimit:
      Type:
        uint8
      Range:
        max: MAXUINT8
        min: MINUINT8
    MaxIntegratorLimit:
      Type:
        uint8
      Range:
        max: MAXUINT8
        min: MINUINT8
    mCtrlCycleDiv:
      Type:
        uint8
      Range:
        max: MAXUINT8
        min: MINUINT8
DriveParam:
    MaxPwmDutyCycle:
      Type:
        uint8
      Range:
        max: MAXUINT8
        min: MINUINT8
    PositionOffset:
      Type:
        uint8
      Range:
        max: MAXUINT8
        min: MINUINT8
    PosModeAcc:
      Type:
        uint8
      Range:
        max: MAXUINT8
        min: MINUINT8
    PosModeSpeedLimit:
      Type:
        uint8
      Range:
        max: MAXUINT8
        min: MINUINT8
    Speed_1:
      Type:
          uint8
        Range:
          max: MAXUINT8
          min: MINUINT8
    Speed_2:
      Type:
        uint8
      Range:
        max: MAXUINT8
        min: MINUINT8
    CalibSpeed:
      Type:
        uint8
      Range:
        max: MAXUINT8
        min: MINUINT8
    SearchRefMarkSpeed:
      Type:
        uint8
      Range:
        max: MAXUINT8
        min: MINUINT8
    PositioningWindow:
      Type:
        uint8
      Range:
        max: MAXUINT8
        min: MINUINT8
    DriveTime:
      Type:
        uint8
      Range:
        max: MAXUINT8
        min: MINUINT8
    NotMoveTime:
      Type:
        uint8
      Range:
        max: MAXUINT8
        min: MINUINT8
    CalibSleepTimeTurnAround:
      Type:
        uint8
      Range:
        max: MAXUINT8
        min: MINUINT8
    ADMeasurementSleepTime:
      Type:
        uint8
      Range:
        max: MAXUINT8
        min: MINUINT8
    DistanceToEndStopMM:
      Type:
        uint8
      Range:
        max: MAXUINT8
        min: MINUINT8
SavePosition:
    Type:
      Uint32
    Range:
    min: 00
    max: UINT_MAX


